[project]
name = "whl-filterpy"
version = "1.4.5"
dependencies = [
  "numpy",
  "scipy",
  "matplotlib",
]
requires-python = ">= 3.6"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"



