[project]
name = "whl-filterpy"
version = "1.4.5"
dependencies = [
  "numpy",
  "scipy",
  "matplotlib",
]
requires-python = ">= 3.11"

[build-system]
requires = [
  "setuptools >= 70.2.0",
  "wheel",
  "numpy",
  "scipy",
  "matplotlib",
]
build-backend = "setuptools.build_meta"



