[project]
name = "whl-filterpy"
version = "1.4.5"

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
  "numpy",
  "scipy",
  "matplotlib",
]

[project]
requires-python = ">= 3.6"
