name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.19.2
        # env:
        #   CIBW_SOME_OPTION: value
        #    ...
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
      # Used to host cibuildwheel
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11' 

      # - name: Install cibuildwheel
      #   run: python -m pip install cibuildwheel==2.19.2 numpy scipy matplotlib

      # - name: Build wheels
      #   run: python setup.py bdist_wheel; find

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: filterpy-1.4.5-py3-none-any.whl
      #     path: dist/filterpy-1.4.5-py3-none-any.whl
